{% set php_version = env('PHP_VERSION') %}
FROM debian:stretch-slim

ENV PHP_VERSION '{{ php_version }}'

{% block php_repo %}
{% if php_version != '7.0' %}

RUN apt-get update \
    && apt-get install -y apt-transport-https lsb-release ca-certificates wget curl \
    && wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg \
    && echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/php.list \
    && rm -rf /var/lib/apt/lists/*
{% endif %}
{% endblock %}

RUN apt-get update && \
    apt-get install -y --force-yes php${PHP_VERSION} php${PHP_VERSION}-soap php${PHP_VERSION}-fpm  \
        php${PHP_VERSION}-mysql php${PHP_VERSION}-apcu php${PHP_VERSION}-gd php${PHP_VERSION}-imagick php${PHP_VERSION}-curl php${PHP_VERSION}-common \
        php${PHP_VERSION}-intl php${PHP_VERSION}-memcached php${PHP_VERSION}-dom php${PHP_VERSION}-bcmath php${PHP_VERSION}-zip \
        php${PHP_VERSION}-mbstring php${PHP_VERSION}-ldap php${PHP_VERSION}-gmp php${PHP_VERSION}-xdebug gnupg && \
        rm -rf /var/lib/apt/lists/* && \
        mkdir -p /run/php/ && \
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin/ --filename=composer

COPY xdebug/xdebug.ini /etc/php/${PHP_VERSION}/mods-available/
RUN rm /etc/php/${PHP_VERSION}/fpm/conf.d/20-xdebug.ini /etc/php/${PHP_VERSION}/cli/conf.d/20-xdebug.ini && \
    ln -s /etc/php/${PHP_VERSION}/mods-available/xdebug.ini /etc/php/${PHP_VERSION}/fpm/conf.d/20-xdebug.ini && \
    ln -s /etc/php/${PHP_VERSION}/mods-available/xdebug.ini /etc/php/${PHP_VERSION}/cli/conf.d/20-xdebug.ini


RUN set -eux; \
    apt-get update; \
    apt-get install -y gosu; \
    rm -rf /var/lib/apt/lists/*; \
    # verify that the binary works
    gosu nobody true

RUN apt-get update && apt-get install -y openssl git && apt-get purge -y --auto-remove

COPY entrypoint.sh /usr/local/bin/entrypoint
RUN chmod 700 /usr/local/bin/entrypoint && chown root:root /usr/local/bin/entrypoint

ENV APP_ENV 'dev'

RUN \
  sed -i "s/^memory_limit = .*/memory_limit = \"\${PHP_CLI_MEMORY_LIMIT}\"/g" "/etc/php/$PHP_VERSION/cli/php.ini"; \
  \
  sed -i "s/^;\?access\.log = .*/access.log = \/proc\/self\/fd\/2/g" "/etc/php/$PHP_VERSION/fpm/pool.d/www.conf"; \
  sed -i "s/^;\?error_log = .*/error_log = \/proc\/self\/fd\/2/g" "/etc/php/$PHP_VERSION/fpm/php-fpm.conf"; \
  sed -i "s/^;\?catch_workers_output = .*/catch_workers_output = yes/g" "/etc/php/$PHP_VERSION/fpm/pool.d/www.conf"; \
  sed -i "s/^;\?clear_env = .*/clear_env = no/g" "/etc/php/$PHP_VERSION/fpm/pool.d/www.conf"; \
  \
  sed -i "s/^memory_limit = .*/memory_limit = \"\${PHP_FPM_MEMORY_LIMIT}\"/g" "/etc/php/$PHP_VERSION/fpm/php.ini"; \
  sed -i "s/max_execution_time = 30/max_execution_time = \"\${PHP_FPM_MAX_EXEC_TIME}\"/g" "/etc/php/$PHP_VERSION/fpm/php.ini"; \
  sed -i "s/^user = .*/user = \"\${PHP_FPM_USER}\"/g" "/etc/php/$PHP_VERSION/fpm/pool.d/www.conf"; \
  sed -i "s/^group = .*/group = \"\${PHP_FPM_GROUP}\"/g" "/etc/php/$PHP_VERSION/fpm/pool.d/www.conf"; \
  sed -i "s/^listen = .*/listen = \"\${PHP_FPM_LISTEN}\"/g" "/etc/php/$PHP_VERSION/fpm/pool.d/www.conf"; \
  sed -i "s/^pm\.max_children = .*/pm.max_children = \"\${PHP_FPM_PM_MAX_CHILDREN}\"/g" "/etc/php/$PHP_VERSION/fpm/pool.d/www.conf"; \
  sed -i "s/^pm\.start_servers = .*/pm.start_servers = \"\${PHP_FPM_PM_START_SERVERS}\"/g" "/etc/php/$PHP_VERSION/fpm/pool.d/www.conf"; \
  sed -i "s/^pm\.min_spare_servers = .*/pm.min_spare_servers = \"\${PHP_FPM_PM_MIN_SPARE_SERVERS}\"/g" "/etc/php/$PHP_VERSION/fpm/pool.d/www.conf"; \
  sed -i "s/^pm\.max_spare_servers = .*/pm.max_spare_servers = \"\${PHP_FPM_PM_MAX_SPARE_SERVERS}\"/g" "/etc/php/$PHP_VERSION/fpm/pool.d/www.conf"; \
  sed -i "s/^;\?request_terminate_timeout = .*/request_terminate_timeout = \"\${PHP_FPM_REQUEST_TERMINATE_TIMEOUT}\"/g" "/etc/php/$PHP_VERSION/fpm/pool.d/www.conf";

ENV PHP_CLI_MEMORY_LIMIT '128M'

ENV PHP_FPM_MEMORY_LIMIT '128M'
ENV PHP_FPM_USER 'docker'
ENV PHP_FPM_GROUP 'docker'
ENV PHP_FPM_LISTEN '0.0.0.0:9000'
ENV PHP_FPM_PM_MAX_CHILDREN '5'
ENV PHP_FPM_PM_START_SERVERS '2'
ENV PHP_FPM_PM_MIN_SPARE_SERVERS '1'
ENV PHP_FPM_PM_MAX_SPARE_SERVERS '3'
ENV PHP_FPM_REQUEST_TERMINATE_TIMEOUT '0'
ENV PHP_FPM_MAX_EXEC_TIME '30'

WORKDIR /data/application

ENTRYPOINT ["/usr/local/bin/entrypoint"]

CMD ["php-fpm{{ php_version }}", "-F"]

EXPOSE 9000
