version: "3.4"
services:
  nginx:
    image: nginx:1.15
    volumes:
      - ./public:/data/application/public
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - php
    ports:
      - 8080:80
    environment:
      VIRTUAL_HOST: xdebug-test-app.develop
  php:
    image: kolemp/php-dev:7.2
    volumes:
      - .:/data/application
    environment:
      XDEBUG_ENABLE: 1
      APP_ENV: dev
      USER_ID: ${UID}

