version: 2

.test_job_template: &test_job_template
    machine:
        enabled: true
        docker_layer_caching: true
    steps:
        - checkout
        - run:
              command: |
                  make build PHP_VERSION=$PHP_VERSION
                  curl -fsSL https://goss.rocks/install | sudo sh
                  GOSS_VARS=vars.yaml GOSS_OPTS="--retry-timeout=30s" dgoss run -e PHP_VERSION $REPO_NAME:$PHP_VERSION
                  GOSS_VARS=vars.yaml GOSS_OPTS="--retry-timeout=30s" dgoss run -e PHP_VERSION -e XDEBUG_ENABLE='1' -e USER_ID="1000" $REPO_NAME:$PHP_VERSION

.build_job_template: &build_job_template
    machine:
        enabled: true
        docker_layer_caching: true
    steps:
        - checkout
        - run:
            command: |
                export NOWDATE=$(date '+%Y%m%d%H%M%S')

                make build PHP_VERSION=$PHP_VERSION

                curl -fsSL https://goss.rocks/install | sudo sh
                GOSS_VARS=vars.yaml GOSS_OPTS="--retry-timeout=30s" dgoss run -e PHP_VERSION $REPO_NAME:$PHP_VERSION
                GOSS_VARS=vars.yaml GOSS_OPTS="--retry-timeout=30s" dgoss run -e PHP_VERSION -e XDEBUG_ENABLE='1' -e USER_ID="1000" $REPO_NAME:$PHP_VERSION

                docker login -u $DOCKER_USER -p $DOCKER_PASS
                docker push $REPO_NAME:$PHP_VERSION
                docker tag $REPO_NAME:$PHP_VERSION $REPO_NAME:$PHP_VERSION-$NOWDATE
                docker push $REPO_NAME:$PHP_VERSION-$NOWDATE
                if [ "$PHP_VERSION" == "7.3" ]; then
                    docker tag $REPO_NAME:$PHP_VERSION $REPO_NAME:latest
                    docker push $REPO_NAME:latest
                fi

jobs:
    test_dev_70:
        <<: *test_job_template
        environment:
            PHP_VERSION: "7.0"
            APP_ENV: "dev"
            REPO_NAME: "kolemp/php-dev"
    test_dev_71:
        <<: *test_job_template
        environment:
            PHP_VERSION: "7.1"
            APP_ENV: "dev"
            REPO_NAME: "kolemp/php-dev"
    test_dev_72:
        <<: *test_job_template
        environment:
            PHP_VERSION: "7.2"
            APP_ENV: "dev"
            REPO_NAME: "kolemp/php-dev"
    test_dev_73:
        <<: *test_job_template
        environment:
            PHP_VERSION: "7.3"
            APP_ENV: "dev"
            REPO_NAME: "kolemp/php-dev"

    test_prod_70:
        <<: *test_job_template
        environment:
            PHP_VERSION: "7.0"
            APP_ENV: "prod"
            REPO_NAME: "kolemp/php"
    test_prod_71:
        <<: *test_job_template
        environment:
            PHP_VERSION: "7.1"
            APP_ENV: "prod"
            REPO_NAME: "kolemp/php"
    test_prod_72:
        <<: *test_job_template
        environment:
            PHP_VERSION: "7.2"
            APP_ENV: "prod"
            REPO_NAME: "kolemp/php"
    test_prod_73:
        <<: *test_job_template
        environment:
            PHP_VERSION: "7.3"
            APP_ENV: "prod"
            REPO_NAME: "kolemp/php"

    build_dev_70:
        <<: *build_job_template
        environment:
            PHP_VERSION: "7.0"
            APP_ENV: "dev"
            REPO_NAME: "kolemp/php-dev"
    build_dev_71:
        <<: *build_job_template
        environment:
            PHP_VERSION: "7.1"
            APP_ENV: "dev"
            REPO_NAME: "kolemp/php-dev"
    build_dev_72:
        <<: *build_job_template
        environment:
            PHP_VERSION: "7.2"
            APP_ENV: "dev"
            REPO_NAME: "kolemp/php-dev"
    build_dev_73:
        <<: *build_job_template
        environment:
            PHP_VERSION: "7.3"
            APP_ENV: "dev"
            REPO_NAME: "kolemp/php-dev"

    build_prod_70:
        <<: *build_job_template
        environment:
            PHP_VERSION: "7.0"
            APP_ENV: "prod"
            REPO_NAME: "kolemp/php"
    build_prod_71:
        <<: *build_job_template
        environment:
            PHP_VERSION: "7.1"
            APP_ENV: "prod"
            REPO_NAME: "kolemp/php"
    build_prod_72:
        <<: *build_job_template
        environment:
            PHP_VERSION: "7.2"
            APP_ENV: "prod"
            REPO_NAME: "kolemp/php"
    build_prod_73:
        <<: *build_job_template
        environment:
            PHP_VERSION: "7.3"
            APP_ENV: "prod"
            REPO_NAME: "kolemp/php"

workflows:
  version: 2
  build_and_push:
      jobs:
          - test_dev_70:
                filters:
                    branches:
                        ignore: master
          - test_dev_71:
                filters:
                    branches:
                        ignore: master
          - test_dev_72:
                filters:
                    branches:
                        ignore: master
          - test_dev_73:
                filters:
                    branches:
                        ignore: master
          - test_prod_70:
                filters:
                    branches:
                        ignore: master
          - test_prod_71:
                filters:
                    branches:
                        ignore: master
          - test_prod_72:
                filters:
                    branches:
                        ignore: master
          - test_prod_73:
                filters:
                    branches:
                        ignore: master
          - build_dev_70:
                filters:
                    branches:
                        only: master
          - build_dev_71:
                filters:
                    branches:
                        only: master
          - build_dev_72:
                filters:
                    branches:
                        only: master
          - build_dev_73:
                filters:
                    branches:
                        only: master
          - build_prod_70:
                filters:
                    branches:
                        only: master
          - build_prod_71:
                filters:
                    branches:
                        only: master
          - build_prod_72:
                filters:
                    branches:
                        only: master
          - build_prod_73:
                filters:
                    branches:
                        only: master
